services:
  # Botumuz için bir "Background Worker" (Arka Plan Çalışanı) tanımlıyoruz.
  - type: worker
    # Render'da görünecek olan isim.
    name: motivasyon-jarvis
    # Çalışacağı sunucunun konumu.
    region: frankfurt
    # Hangi GitHub branch'inin kullanılacağı.
    branch: main
    # Çalışma ortamı.
    runtime: python
    # Kurulum sırasında çalışacak komut.
    buildCommand: "pip install -r requirements.txt"
    # Botu başlatacak olan asıl komut.
    startCommand: "python bot.py"
    # ÜCRETSİZ planı kullanacağımızı belirtiyoruz.
    plan: free
    # Gizli bilgilerimizi (token'lar) tanımlıyoruz.
    # DİKKAT: Değerleri buraya yazmıyoruz! Render bize bunları soracak.
    envVars:
      - key: TELEGRAM_TOKEN
        from_value: true # Değeri Render arayüzünden alacağımızı belirtir.
      - key: OPENROUTER_API_KEY
        from_value: true
      - key: ADMIN_USER_ID
        from_value: true